apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: {{ .Values.ingressClassName }}
  rules:
    - host: {{ .Values.host }}
      http:
        paths:
          {{- range $name, $route := .Values.routes }}
          - path: {{ $route.path }}(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ $route.serviceName }}
                port:
                  number: {{ $route.servicePort }}
          {{- end }}
